config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root to: "pages#home"

  get 'posts/:id/delete_image', to: 'posts#delete_image', as: 'remove_cover_image'

  devise_scope :user do
    get 'kafkaontheshore', to: 'devise/sessions#new'
  end

  get "/tabs" => "pages#tabs"

  get "/home" => "pages#home"

  resources :posts do
    collection do
      get :action
    end

    member do
      get :publish
      get :hide
      get :enable_comments
      get :disable_comments
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :cover_image, styles: {medium: "300x300>", thumb: "100x100>"} #default_url: "/images/:style/missing.png"
	validates_attachment_content_type :cover_image, content_type: /\Aimage\/.*\Z/
	attr_writer :current_step #, :step # for security and remembering step on first 'Next >>'
	validates_presence_of :title, :author, :composed_on, :body, :if => :public_step? 
	validates_presence_of :summary, :if => :private_step?

  belongs_to :users
  belongs_to :sections


	  def current_step
    		#@post = Post.find(params[:id])
    		@current_step || steps.first
  	end

  	def steps
    		%w[public_form_elems private_form_elems]
  	end

  	def next_step
  		self.current_step = steps[steps.index(current_step)+1]
  	end

  	def previous_step
  		self.current_step = steps[steps.index(current_step)-1]
  	end

  	def first_step?
  		current_step == steps.first
  	end

  	def first_step!
  		current_step = steps.first
  	end

  	def last_step?
  		current_step == steps.last
  	end

  	def public_step?
  		current_step == "public_form_elems"
  	end

  	def private_step?
  		current_step == "private_form_elems"
  	end

  	def all_elems_valid?
  		steps.all? do |step|
  			self.current_step = step
  			valid?
  		end
  	end

  	def hash_to_post(h)
  		h.each { |k, v| public_send("#{k}=", v)}
  	end

    def self.search(search)
      if search
        where('title LIKE ?', "%#{search}%")
      else
        all
      end
    end

end
  # what does attr_accessible do?

  %#__END__

  put image sizes as percent not absolute sizes

  #

app/models/section.rb
class Section < ActiveRecord::Base
	has_many :posts
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show]
  helper_method :sort_column, :sort_direction
  
  # GET /posts
  # GET /posts.json
  def index
    @sections = Section.all

    if current_user.admin?
      if filter_field.nil?
        @posts = Post.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
      else
        if filter_field == "section_id"
          @posts = Post.search(params[:search]).where(section_id: filter_value.to_i).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page]).paginate(:per_page => 10, :page => params[:page])
        elsif filter_field == "author"
          @posts = Post.search(params[:search]).where(user_id: filter_value.to_i).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
        elsif filter_field == "series_id"
          @posts = Post.search(params[:search]).where(series_id: filter_value.to_i).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
        end     
      end
      @users = User.all.order("id")
    else
      if filter_field.nil?
        @posts = Post.search(params[:search]).where(user_id: current_user.id).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
      else
        if filter_field == "section_id"
          @posts = Post.search(params[:search]).where(user_id: current_user.id).where(section_id: filter_value.to_i).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
        elsif filter_field == "author"
          @posts = Post.search(params[:search]).where(user_id: current_user.id).where(user_id: filter_value.to_i).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
        elsif filter_field == "series_id"
          @posts = Post.search(params[:search]).where(user_id: current_user.id).where(series_id: filter_value.to_i).order(sort_column + ' ' + sort_direction).paginate(:per_page => 10, :page => params[:page])
        end     
      end
    end
    
    #@posts = Post.all
    session.delete(:post_params)                    # In case back is pressed
    session.delete(:post_step)                      # remove sessions variables for post form
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    session.delete(:post_params)                    # In case back is pressed FUNCTION??
    session.delete(:post_step)                      # remove sessions variables for post form
  end

  # GET /posts/new
  def new
    session[:post_params] ||= {}
    @post = Post.new
    @post.first_step!                               # since create derives current step from the session
    session[:post_step] = @post.current_step        # session must store step.first in new
    #session[:post_step] = @post.steps.first # words if attr_accessor has steps, SECURITY RISK
  end

  # GET /posts/1/edit
  def edit
    if !(current_user.admin? || @post.user_id == current_user.id)
      redirect_to posts_path, alert: 'Access denied'
    end
    session[:post_params] = {}
    @post.first_step!                               
    session[:post_step] = @post.current_step
    
  end

  # POST /posts
  # POST /posts.json
  # PROBLEM #1: Cookie overflow
  # Solution #1: remove image from session[:post_param] by stroing it in an intermediate 
  #              variable and reattaching it to @post BUT HOW???
  # Solution #2: replace cookies with ActiveRecordStorage BUT MAJOR SECURITY RISK IS 
  #              a million people try to save images in ActiveRecordStorage at the same 
  #              time
  #
  # PROBLEM #2: Image cannot be stored in session_store
  # Solution #1: remove image from post_params before deep_merging with sessions, and then
  #              reattach to @post using a temp variable
  #
  # PROBLEM #3: Once image is cleaved, ruby debugger loses formatting but it does show
  #             temp variable holding image HOW TO FIX THIS??????
  #
  def create
    session[:post_params].deep_merge!(post_params.except(:cover_image)) if post_params
    tmp_img = post_params[:cover_image]
    @post = Post.new(session[:post_params])
    @sections = Section.all         # NECESSARRY BECAUSE session may hold
    @post.cover_image = tmp_img                     # data from prior steps
    @post.current_step = session[:post_step]
    
    if @post.valid?
      if params[:previous_button]
        @post.previous_step
      elsif @post.last_step? 
        @post.user_id = current_user.id ################################################
        @post.save if @post.all_elems_valid?
      else
        @post.next_step
      end
      session[:post_step] = @post.current_step
    end

    if @post.new_record?
      render 'new'
    else
      redirect_to @post, notice: 'Post was successfully created'
    end 

    # WHAT IS ALL THIS JUNK??
    %#respond_to do |format|
      
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end #

  end 

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update

    if !(current_user.admin? || @post.user_id == current_user.id)
      redirect_to posts_path, alert: 'Access denied'
    end

    session[:post_params].deep_merge!(post_params.except(:cover_image))
    img_before_update = true
    if @post.cover_image_file_size.nil?
      img_before_update = false
      tmp_img = post_params[:cover_image]
    else
      tmp_img = @post.cover_image
    end
    @post.hash_to_post(session[:post_params])
    @post.cover_image = tmp_img 
    @post.current_step = session[:post_step]
    @sections = Section.all

    if @post.valid?
      if params[:previous_button]
        @post.previous_step
      elsif @post.last_step?
        @post.user_id = current_user.id 
        @post.update(post_params) if @post.all_elems_valid?
      else
        @post.next_step
      end
    end

    session[:post_step] = @post.current_step

    if @post.updated_at_changed? != nil           # WHY IS updated_at_changed? RETURNING FALSE
      redirect_to @post, notice: 'Post was successfully updated'
    else
      render 'edit' 
    end
    %#
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end #
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy

    if !(current_user.admin? || @post.user_id == current_user.id)
        redirect_to posts_path, alert: 'You cannot delete articles that do not belong to you'
    end

    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_image

    if !(current_user.admin? || @post.user_id == current_user.id)
      redirect_to posts_path, alert: 'Access denied'
    end

    @post = Post.find(params[:id])
    @post.cover_image.destroy
    @post.save
    #@post.save

    #redirect_to :back, notice: 'HERE'
    @post.current_step = session[:post_step]
    render 'edit'
  end

  def action


    if !params[:post_ids].nil?
      params[:post_ids].each do |id|
        post = Post.find(id.to_i)

        if params[:delete_selected]
            post.destroy
        elsif params[:publish_selected]
            post.publish = true
        elsif params[:hide_selected]
            post.publish = false
        elsif params[:enable_comments_for_selected]
            post.commenting = true
        elsif params[:disable_comments_for_selected]
            post.commenting = false
        end

        post.save
      end
    end

    redirect_to posts_path
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
        @post = Post.find(params[:id]) 
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {}).permit(:title, :body, :composed_on, :summary, :author, :cover_image, :section_id, :publish, :commenting)
    end

    def sort_column
      Post.column_names.include?(params[:sort]) ? params[:sort] : "composed_on"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
    end

    def filter_field
      Post.column_names.include?(params[:filter_by]) ? params[:filter_by] : nil
    end

    def filter_value 
      params[:value]
    end

end

__END__

put deletion of sessions variables in update and save instead of index

app/helpers/posts_helper.rb
module PostsHelper
	
	
end

app/views/posts/_form.html.erb
<%= javascript_include_tag 'postjs' %>

<%= form_for(@post, :html => {:class => "ui form", :id => "create_post_form"}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="contents">
      <%= render "#{@post.current_step}_step", :f => f %>
  </div>

  <div class="post-form-buttons">
    <%= f.submit "<< Previous", :name => "previous_button", :class => "ui left floated button"  unless @post.first_step? %>
    <% button_label = "Next >>" %>
    <% if @post.last_step? %>
      <% button_label = "Submit" %>
      <% button_class = "ui right floated primary button" %>
    <% else %>
      <% button_class = "ui right floated button"%>
    <% end %>
    <%= f.submit button_label, :class => button_class %>
  </div>
<% end %>

app/views/posts/_private_form_elems_step.html.erb
<h2>Private</h2>
<div class="field">
  <%= f.label :cover_image %>

  <div class="cover_image_preview">
    <% if (@post.cover_image.file?) %>
      <%= image_tag @post.cover_image.url, :class => "post-cover-image" %>
    <% else %>
      <img class="post-cover-image"/>
    <% end %>
  </div>

  <div class="post-form-image-buttons">
    <div class="ui left floated button" id="file-field-button-aesthetic-hack">
      Attach
      <%= f.file_field(:cover_image, id: 'cover_image_uploader', class: 'ui button', title: '') %>
    </div>
    <% if (@post.persisted? && @post.cover_image.file?) %>
      <%= link_to "Remove", remove_cover_image_path, :method => :get, :class => "ui right floated button" %>
    <% end %> <br>
  </div>
  
</div>
<div class="field">
  <%= f.label :summary %><br />
  <%= f.text_area :summary, :id => "post-summary-editor" %>
</div>


<div class="field">
<%= f.label :section_id %>
<div class="ui selection dropdown">
  <%= f.hidden_field :section_id %>
  <i class="dropdown icon"></i>
  <div class="default text">None</div>
  <div class="menu">
    <% @sections.each do |section| %>
    <div class="item" data-value="<%= section.id %>"><%= section.title %></div>
    <% end %>
  </div>
</div>
</div>


<div class="inline fields">
  <%= f.label :publish %>
  <div class="ui toggle checkbox">
    <%= f.check_box :publish %>
    <label></label>
  </div>
  
  <%= f.label :commenting %>
  <div class="ui toggle checkbox">
    <%= f.check_box :commenting %>
    <label></label>
  </div>
</div>

<script>
$(function() {
  $('#post-summary-editor').froalaEditor({
    height: 200
  })
});

//$('.cover_image_preview').height(<%  %>);
$('.ui.dropdown').dropdown();

</script>

app/views/posts/_public_form_elems_step.html.erb
<h2>Public</h2>
<div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :author %><br />
  <%= f.text_field :author %>
</div>
<div class="field">
  <%= f.label :composed_on %><br />
  <%= f.date_field :composed_on %>
</div>
<div class="field">
  <%= f.label :body %><br />
  <%= f.text_area :body, :id => "post-body-editor" %>
</div>

<script>
$(function() {
	$('#post-body-editor').froalaEditor({
		height: 500
	})
});
</script>

app/views/posts/edit.html.erb
<div class="ui container" id="post-edit-page">

	<h1>Editing Post</h1>

	<%= render 'form' %>


	<%#button_to 'Back', posts_path, :method => "get", :class => "ui button" %>

	<!--<div class="post-edit-page-back-button"> -->
	<%= button_to 'Back', posts_path, :method => "get", :class => "ui button", :id => "post-edit-page-back-button" %>
	<!-- </div> -->



	<%# link_to 'Show', @post %> 
	<%# link_to 'Back', posts_path %>

</div>

app/views/posts/index.html.erb
<div class="ui top attached menu">

    <div class="ui dropdown item">
      Actions
      <i class="dropdown icon"></i>
      <div class="menu">
        <%= form_tag action_posts_path, :method => :get do %>
        <%= submit_tag 'Publish', name: "publish_selected", class: "item" %>
        <%= submit_tag 'Hide', name: "hide_selected", class: "item" %>
        <%= submit_tag 'Enable Commenting', name: "enable_comments_for_selected", class: "item" %>
        <%= submit_tag 'Disable Commenting', name: "disable_comments_for_selected", class: "item" %>
        <%= submit_tag 'Delete', name: "delete_selected", class: "item" %>
        <% if current_user.admin? %>
          <div class="item">Add to Slider</div>
          <div class="item">Clear Slider</div>
          <%= link_to 'Create New User', new_user_registration_path, class: "item" %>
          <div class="item">Create Section</div>
          <div class="item">Create Series</div>
          <%= link_to 'Go to Console', users_path, class: "item" %>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to 'Sign Out', destroy_user_session_path, class: "item", :method => :delete %>
        <% end %>
        <% end %>
      </div>
    </div>

    <div class="ui dropdown item">
      Navigate
      <i class="folder icon"></i>
      <div class="menu">
        
        <div class="item">Sections
          <div class="menu">
            <% @sections.each do |section| %>  
            <div class="item"><%# link_to section.title, posts_path, name: "section_#{section.id}"%><%= filterable(section, "section") %></div>
            <% end %>
            <div class="item"><%= filterable("All", "section") %></div>
          </div>
        </div>

        <div class="item">Series
            <div class="menu">
            <div class="item">Immigration</div>
            <div class="item">Death on Rails</div>
            <div class="item">All</div>
            </div>
        </div>
        

        <% if current_user.admin? %>
          <div class="item">Authors
              <div class="menu">
              <%  @users.each do |user| %>
              <div class="item"><%= filterable(user, "author") %></div>
              <% end %>
              <div class="item"><%= filterable("All", "author") %></div>
              </div>
          </div>
        <% end %>

        <div class="item"><%= filterable("Clear Filters", "reset") %></div>

      </div>
    </div>

    <script>
      $('.ui.dropdown')
        .dropdown()
      ;
    </script>

    <%= form_tag posts_path, :method => 'get' do %>
    <div class="ui icon input">
      <i class="search icon"></i>
      
        <%= text_field_tag :search, params[:search] %>
      
      <!--input type="text" placeholder="Search..."-->
    </div>
    <% end %>

    <div class="item" id="post-index-new-button">
    <%= link_to 'New', new_post_path %>
    <i class="write icon"></i>
    </div>
</div>



<div class="ui container" id="post-index-page">
  <table class="ui unstackable table" id="private-index-table">
    <thead>
      <tr>
        <th id="checkbox"></th>
        <th id="composed"><%= sortable "composed_on" %>
        </th>
        <th id="created"><%= sortable "created_at" %></th>
        <th id="description">Description</th>
        <th id="published">Published</th>
        <th id="commenting">Commenting</th>
        <th id="rating"><%= sortable "rating" %></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <%# link_to(post) do %>
          <tr>
            <td class="checkbox-column"><%= check_box_tag "post_ids[]", post.id %></td>
            <td class="created-column"><%= post.composed_on.to_formatted_s(:long) %></td>
            <td class="composed-column"><%= post.created_at.to_date.to_formatted_s(:long) %></td>
            <td class="description-body">
              <h5><%= post.title %></h5>
              <div class="fr-view"><%= post.body.html_safe %></div>
              <div class="index-post-buttons">
                <%= link_to post do %>
                  <i class="black external icon"></i>
                <% end %>
                <%= link_to edit_post_path(post) do %>
                  <i class="blue write icon"></i>
                <% end %>
                <%= link_to post, method: :delete do %>
                  <i class="red trash icon"></i>
                <% end %>
              </div>
            </td>
            <td>
              <div class="ui toggle checkbox">
                <%= check_box_tag 'publish', post.id, post.publish %>
                <label></label>
              </div>
            </td>

            <td>
              <div class="ui toggle checkbox">
                <%= check_box_tag 'commenting', post.id, post.commenting %>
                <label></label>
              </div>
            </td>
            <td><%= post.rating %></td>
          </tr>
        <%# end %>
      <% end %>
    </tbody>
  </table>
  
</div>

<%= will_paginate @posts %>

<%# end %>

app/views/posts/new.html.erb
<div class="ui container" id="post-new-page">

	<h1>Create New Post</h1>

	<%= render 'form' %>

	<%= button_to 'Back', posts_path, :method => "get", :class => "ui button", :id => "post-new-page-back-button" %>

</div>

app/views/posts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<% if !@post.cover_image.size.nil? %>
	<div class="post-show-page-cover" style="background-image: url('<%= @post.cover_image.url %>');">
		<h1><%# @post.title %></h1>
	</div>
<% end %>


<div class="ui container" id="post-show-page">

	<h1><%= @post.title %></h1>
	<p>Written by <%= @post.author %> on <%= @post.composed_on%></p>

	<div class="fr-view">
		<%= @post.body.html_safe %>
	</div>

	<div class="post-show-buttons">
		<%= button_to 'Edit', edit_post_path(@post), :method => "get" , :class => "ui right floated button"%> 
		<%= button_to 'Back', posts_path, :method => "get", :class => "ui left floated button"%>
	</div>

</div>

<div class="ui container" id="post-sharing-and-rating">

</div>

<div class="ui container" id="post-comments">

</div>

<%# link_to 'Edit', edit_post_path(@post) %>
<%# link_to 'Back', posts_path %>