config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  root to: "pages#home"

  get 'posts/:id/delete_image', to: 'posts#delete_image', as: 'remove_cover_image'

  devise_scope :user do
    get 'kafkaontheshore', to: 'devise/sessions#new'
  end

  get "/tabs" => "pages#tabs"

  get "/home" => "pages#home"

  resources :posts do
    collection do
      get :action
    end

    member do
      get :publish
      get :hide
      get :enable_comments
      get :disable_comments
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DustandsepiaComV1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%# Methods to add images%>
  <%# image_tag @post.cover_image.url %>
  <%# image_tag @post.cover_image.url(:medium) %>
  <%# image_tag @post.cover_image.url(:thumb) %>
</head>
<body>

<div class="ui top fixed inverted borderless menu">

  <div class="item" id="dns-logo">
    <%= link_to 'D&S', root_path, :method => "get", :class => "logo"%>
    <% if user_signed_in? %>
    <%= link_to raw('<i class="icon settings"></i>'.html_safe), posts_path%>
    <% end %>
  </div>

  <div class="ui inverted secondary pointing menu" id="sections-menu">
    <% sections = Section.all %>
    <% sections.each do |section| %>
    <% if params[:tab].to_i == section.id %>
      <% tab_class_name = "active item" %>
    <% else %>
      <% tab_class_name = "item" %>
    <% end %>
    <%= link_to section.title, tabs_path(tab: section.id), class: tab_class_name, name: "#{section.title.downcase}" %>
    <% end %>
  </div>

  <script>
    var menu_width = $("#sections-menu").width();
    var logo_width = $("#dns-logo").width();

    $("#sections-menu").css({left: ($(document).width() / 2) - 1.3*logo_width});
    $("#sections-menu").css("margin-left", "-" + menu_width/2 + "px");

    $(window).resize(function(){
        $("#sections-menu").css({left: ($(document).width() / 2) - 1.3*logo_width});
        $("#sections-menu").css("margin-left", "-" + menu_width/2 + "px");
    });
  </script>

  <div class="ui right inverted menu">
    <div class="item">
      <div class="ui transparent icon input" id="nav-search-bar">
        <input type="text" class="search-bar-input" placeholder="Search..." style="color: white;">
        <i class="search link icon" style="color:white;"></i>
      </div>
    </div>
  </div>

</div>


<div class="ui container" id="website-content"> 
	<%= yield %>
</div>

<% if notice %>
   <div class ="ui message" id="notice">
      <i class="close icon"></i>
      <%= notice %>
  </div>
<% end %>

<% if alert %>
   <div class ="ui message" id="alert">
      <i class="close icon"></i>
      <%= alert %>
  </div>
<% end %>

<script>
  $('.message .close')
  .on('click', function() {
    $(this)
      .closest('.message')
      .transition('fade')
    ;
  });
</script>

<% if Rails.env.development? %>
  <div class="ui container" id="development-debuggers">
  	<%= debug(params) %>
  	<%# debug(session[:post_params]) %>
  	<%= console %>
  </div>
<% end %>

</body>
</html>